fix: correct import for request message type
googleapis/gapic-generator-python pull request #1273
Opened 2022-04-11 00:42 UTC by dizcology

Fixes: https://github.com/googleapis/gapic-generator-python/issues/1263

2022-04-11 19:28 UTC, parthea requested changes
Thanks for fixing this! The changes look good. I noticed a formatting issue in the downstream repo where 2 import statements appear are on the same line. Please could you take a look?
```
+            from google.cloud import resourcemanager_v3from google.iam.v1 import iam_policy_pb2  # type: ignore
```

Steps to re-create the issue:
1) Modify the WORKSPACE file [here](https://github.com/googleapis/googleapis/blob/master/WORKSPACE#L238) to use `local_repository` instead of `http_archive` and point to a clone of gapic generator python with this branch.
2) Run `bazel build //google/cloud/resourcemanager/v3:resourcemanager-v3-py` in the root of googleapis where you modified the `WORKSPACE` file in step 1
3) Run the following in a clone of https://github.com/googleapis/python-resource-manager
```
docker run --rm --user $(id -u):$(id -g)   -v $(pwd):/repo   -v $HOME/git/googleapis/bazel-bin:/bazel-bin   gcr.io/cloud-devrel-public-resources/owlbot-cli:latest copy-bazel-bin   --source-dir /bazel-bin --dest /repo
```
```
docker run --user $(id -u):$(id -g) --rm -v $(pwd):/repo -w /repo gcr.io/cloud-devrel-public-resources/owlbot-python:latest
```
4) Check the diff

2022-04-11 21:09 UTC, dizcology commented
@parthea Thanks for catching that!  I think that is caused by https://github.com/googleapis/gapic-generator-python/blob/main/gapic/samplegen_utils/snippet_index.py#L91, but from the original PR containing that `strip` call I did not see any discussion about why it was needed.  Is there a different styling requirement for these snippets in client method docstrings to have only one blank line before function definition, while in the standalone sample.py file there should be two blank lines?

2022-04-11 21:50 UTC, parthea commented
@dizcology I only see the formatting issue with the imports when I apply the changes from this PR. I don't see the issue in the `main` branch. It could be that the changes in this PR exposed an underlying issue. I haven't debugged that part of the code yet. Would you be interested in adding a test to verify the output of the sample generator? I don't see change changes to the golden files based on the changes in this PR so it's possible that we don't have any checks for the generated sample code.

2022-04-12 00:19 UTC, dizcology commented
Looks like there is some magic in client method docstring rendering that suppresses multiple new lines in some cases, so that strip was not needed after all.

2022-04-13 16:37 UTC, parthea approved these changes

2022-04-13 16:38 UTC, merged