chore: refactor mtls endpoint function
googleapis/gapic-generator-python pull request #1873
Opened 2023-11-24 20:04 UTC by ohmayr

Fixes #<issue_number_goes_here> 🦕

2023-12-01 21:30 UTC, parthea approved these changes
LGTM, just minor observations

2023-12-05 16:13 UTC, ohmayr commented on gapic/templates/%namespace/%name_%version/%sub/services/%service/async_client.py.j2
> +        self._api_endpoint = self._client._api_endpoint
Filed #1883

2023-12-05 20:53 UTC, ohmayr commented on gapic/templates/%namespace/%name_%version/%sub/services/%service/client.py.j2
> -        api_endpoint, client_cert_source_func = self.get_mtls_endpoint_and_cert_source(client_options)
The alternative is not available as of now. I've filed a bug to deprecate this: #1885

2023-12-05 21:34 UTC, parthea approved these changes

2023-12-07 01:06 UTC, vchudnov-g requested changes
Thanks for working on this! Two general notes:

- You are not refactoring the `mtls_endpoint` function. You are not even touching it. So I would change the PR title to be more accurate, something like "inline logic for reading environment variables  and settingclient cert source, api endpoints"

- What is the value of inlining the logic that is in the mtls_endpoint function into the client `__init__` function? I would suggest making those inner functions take parameters and be module-level functions, and then you can test them directly to make sure the logic of each is as you desire.  Then in the test for the `__init__`  function, all you have test is that arbitrary values returned by (mocked versions of) those functions get properly used in the client. Doing this makes your code more modular and thus easier to test and reason about.

Happy to discuss more.

2023-12-07 06:25 UTC, ohmayr commented on gapic/templates/%namespace/%name_%version/%sub/services/%service/client.py.j2
> +        # validate the environment variables
addressed!

2023-12-07 06:25 UTC, ohmayr commented on gapic/templates/%namespace/%name_%version/%sub/services/%service/client.py.j2
> +        def validate_environment_variables():
addressed!

2023-12-07 06:26 UTC, ohmayr commented on gapic/templates/%namespace/%name_%version/%sub/services/%service/client.py.j2
> +            source is None.
addressed!

2023-12-07 06:26 UTC, ohmayr commented on gapic/templates/%namespace/%name_%version/%sub/services/%service/client.py.j2
> +            (2) if `GOOGLE_API_USE_CLIENT_CERTIFICATE` environment variable is "always", use the
addressed!

2023-12-07 06:27 UTC, ohmayr commented on gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
> +    # If ClientOptions.api_endpoint is not set and GOOGLE_API_USE_MTLS_ENDPOINT="auto" and default cert source doesn't exist,
addressed!

2023-12-07 06:27 UTC, ohmayr commented on gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
> +    # If ClientOptions.api_endpoint is not set and GOOGLE_API_USE_MTLS_ENDPOINT="auto" and default cert source exists,
addressed!

2023-12-07 16:25 UTC, ohmayr commented on gapic/templates/%namespace/%name_%version/%sub/services/%service/client.py.j2
> +        self._api_endpoint = get_api_endpoint()
Yes, this PR is a part of alternative 2 in the doc. However, we don't want to deprecate the function until there's an alternative available i.e. users have another way of reading the api endpoint.

So we've decided to keep the function for now, and deprecate it once the TPC changes are in. That'll include access to the api endpoint via a property method.

I've filed a bug to deprecate this method: #1885

2023-12-07 16:38 UTC, ohmayr commented
> * You are not refactoring the `mtls_endpoint` function. You are not even touching it. So I would change the PR title to be more accurate, something like "inline logic for reading environment variables  and settingclient cert source, api endpoints"

You're right! As we were working through it, we figured that it made more sense to not touch the function for now but have inline logic inside the client initialization so that the TPC changes in the design make more sense. Apart from that, the `get_mtls_endpoint_and_cert_source` function does more than what the name suggests, i.e. it isn't restricted to just getting the mtls endpoint. I've updated the PR title to reflect the changes.

> * What is the value of inlining the logic that is in the mtls_endpoint function into the client `__init__` function? I would suggest making those inner functions take parameters and be module-level functions, and then you can test them directly to make sure the logic of each is as you desire.  Then in the test for the `__init__`  function, all you have test is that arbitrary values returned by (mocked versions of) those functions get properly used in the client. Doing this makes your code more modular and thus easier to test and reason about.

Having these functions inside the `__init__` function provides us with encapsulation and better readability. By default, python doesn't have private methods i.e. any module level functions are accessible to the user (even the ones that we declare with an underscore to be private and not meant to be used). We probably don't want to support these functions right now.

2023-12-07 17:54 UTC, ohmayr commented on gapic/templates/%namespace/%name_%version/%sub/services/%service/client.py.j2
> +            use_client_cert = os.getenv("GOOGLE_API_USE_CLIENT_CERTIFICATE", "false")
addressed!

2023-12-07 19:46 UTC, vchudnov-g commented on gapic/templates/%namespace/%name_%version/%sub/services/%service/client.py.j2
> +        self._api_endpoint = get_api_endpoint()
Hmm, I see. But in the expected/normal workflow, users shouldn't need to call that function, right? I would think it still makes some sense to deprecate it now. To clarify, deprecation does not mean deletion: we keep the function but say that it is deprecated and will be removed at some point, as the client initialization no longer needs it.

More importantly, this argues for the benefits of not making the code inaccessible via inner functions, but moving it to independent function(s) that the user can access: that way, people who are calling the current function directly now can switch to call the new function directly.

2023-12-13 21:11 UTC, vchudnov-g approved these changes
Looks great! Thanks for doing this @ohmayr !

I have one suggestion to return a real boolean rather than a stringified one, and suggestions for some more checks in your existing tests. Everything else is cosmetic or nitty or deferrable.

2023-12-13 21:17 UTC, vchudnov-g commented
Also, given how this PR wound up, maybe changing the title one more time: ` refactor logic for reading environment variables, and for setting client cert source and api endpoints`

2023-12-18 21:14 UTC, vchudnov-g commented on gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
> +    with mock.patch.dict(os.environ, {"GOOGLE_API_USE_MTLS_ENDPOINT": "never"}):
Could you add a stanza for this case: `with mock.patch.dict(os.environ, {"GOOGLE_API_USE_MTLS_ENDPOINT": "never"}):`? (You're covering the default and the unrecognized value, but what about the explictly set `auto`?

And similarly for `with mock.patch.dict(os.environ, {"GOOGLE_API_USE_CLIENT_CERTIFICATE": false"}):` explicitly

2023-12-18 21:15 UTC, vchudnov-g commented on gapic/templates/tests/unit/gapic/%name_%version/%sub/test_%service.py.j2
> +    # If ClientOptions.api_endpoint is set and GOOGLE_API_USE_CLIENT_CERTIFICATE="true",
ping

2023-12-18 21:16 UTC, vchudnov-g approved these changes
Looks good. I pinged you on a couple of comments from the last review that would still be a good idea.

And also, please see my comments about updating the PR title to be more accurate given our changes.

Thank you for doing this!

2023-12-18 22:08 UTC, vchudnov-g approved these changes

2023-12-18 22:30 UTC, merged